name: 🔑 Request Mirror Token
description: Запрос токена для запуска зеркала
title: "[Mirror Request]: <Ваше название>"
labels: ["mirror-request"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за желание помочь проекту! Заполните форму, и мы пришлем токен.
  - type: input
    id: hosting
    attributes:
      label: Хостинг / Провайдер
      description: Где расположен сервер? (например: Aeza, Timeweb, Home ISP)
      placeholder: Selectel SPB
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Контакт для связи (Telegram)
      description: Куда прислать токен? (Обязательно укажите @username)
      placeholder: @my_telegram_nick
    validations:
      required: true
